name: CD

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Check files
        run: ls -al

      - name: Create .env
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          touch ./.env
          echo "$ENV" > ./.env

      - name: Check if .env file exists
        run: ls -l .env

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache npm
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Echo npm-cache-dir
        run: echo ${{steps.npm-cache-dir.outputs.dir}}

      - name: Log npm-cache status
        run: |
          if [[ '${{ steps.npm-cache.outputs.cache-hit }}' == 'true' ]]; then
            echo "npm cache hit!!";
          else
            echo "npm cache miss";
          fi

      - name: Install packages
        run: npm install

      - name: Cache .next/cache
        uses: actions/cache@v4
        id: 'next-cache'
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Log next-cache status
        run: |
          if [[ '${{ steps.next-cache.outputs.cache-hit }}' == 'true' ]]; then
            echo ".next/cache cache hit!!";
          else
            echo ".next/cache cache miss";
          fi

      - name: ls -al
        run: ls -al

      - name: Build
        run: npm run build

      - name: ls -al (after build)
        run: ls -al

      - name: Run Unit Tests
        run: npm run test

      - name: Docker build and push
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO: ${{ secrets.DOCKER_REPOSITORY }}
        run: |
          docker login -u $USERNAME -p $PASSWORD
          docker build -t $USERNAME/$REPO:${GITHUB_SHA::7} -t $USERNAME/$REPO:latest .
          docker push $USERNAME/$REPO:${GITHUB_SHA::7}
          docker push $USERNAME/$REPO:latest

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          REPO: ${{ secrets.DOCKER_REPOSITORY }}
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA,REPO
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/$REPO:${GITHUB_SHA::7}
            docker tag ${{ secrets.DOCKER_USERNAME }}/$REPO:${GITHUB_SHA::7} $REPO
            docker stop $REPO
            docker rm $REPO
            docker run -d --name $REPO -p 80:3000 $REPO
